# Required metadata
sonar.projectKey=br.com.rodrigo:poc-redis-demo
sonar.projectName=Redis Demo
sonar.projectVersion=1.0.0

# Source information
sonar.sources=src/main/java
sonar.java.binaries=target/classes
sonar.java.source=21

# Tests
sonar.tests=src/test/java
sonar.junit.reportPaths=target/surefire-reports
sonar.jacoco.reportPaths=target/jacoco.exec
sonar.java.coveragePlugin=jacoco

# Encoding of the source code
sonar.sourceEncoding=UTF-8

# Exclusions for code coverage
sonar.coverage.exclusions=**/RedisDemoApplication.java,**/model/**,**/dto/**,**/exception/ResourceNotFoundException.java,**/config/TestRedisConfiguration.java

# Exclusions for duplication detection
sonar.cpd.exclusions=**/model/**,**/dto/**

# Quality gate settings
sonar.qualitygate.wait=true